# https://taskfile.dev

version: '3'

tasks:
  run:
    desc: run go app
    cmds:
      - go run main.go
    silent: true
  gen:
    desc: generate protocol buffer stubs
    cmds:
      - protoc --proto_path=proto proto/*.proto --go_out=. --go-grpc_out=.
    silent: true